print("proszę wybrać: ")
print("1) Dodawanie")
print("2) Odejmowanie")
print("3) Monżenie")
print("4) Dzielenie")
print("5) Potęgowanie")
print("6) Silnia")
print("7) System binarny (dwójkowy)")
print("8) System oktalny (ósemkowy)")
print("9) System heksadecymalny (szesnastkowy)")
print("10) Wyjście z programu")      